/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run_game: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wgpu_render_bundle_draw: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wgpu_render_bundle_set_pipeline: (a: number, b: bigint) => void;
export const wgpu_render_bundle_draw_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_set_bind_group: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const wgpu_render_bundle_set_vertex_buffer: (a: number, b: number, c: bigint, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_set_push_constants: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_insert_debug_marker: (a: number, b: number) => void;
export const wgpu_render_bundle_pop_debug_group: (a: number) => void;
export const wgpu_render_bundle_set_index_buffer: (a: number, b: bigint, c: number, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_push_debug_group: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d26f778afe4d440: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h19702a69851894c4: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__he33ab63df9443194: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2f78ba2d10ff3a2d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h648124f5ccb916e4: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h95336bcd11dd760f: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h258e951ddd50f47c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hbac0acc1adf59861: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h5f8cf5c1ce1eb0db: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__he0d172362c95ddc2: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
